FROM node:lts as dependencies
RUN mkdir -p /home/app/front-end/web/node_modules && chown -R node:node /home/app/front-end/web

WORKDIR /home/app/front-end/web

COPY package*.json ./
RUN npm install

FROM node:lts as builder
WORKDIR /home/app/front-end/web
COPY . .
COPY --from=dependencies /home/app/front-end/web/node_modules ./node_modules
RUN npm run build

FROM node:lts as runner
WORKDIR /home/app/front-end/web
ENV NODE_ENV production

COPY --from=builder /home/app/front-end/web/next.config.js ./
COPY --from=builder /home/app/front-end/web/public ./public
COPY --from=builder /home/app/front-end/web/.next ./.next
COPY --from=builder /home/app/front-end/web/node_modules ./node_modules
COPY --from=builder /home/app/front-end/web/package.json ./package.json

EXPOSE 3000
CMD ["npm", "start"]